version: 0.2

env:
  secrets-manager:
    DOCKER_USERNAME: "arn:aws:secretsmanager:ap-south-1:825765401880:secret:Docker-Credentials-JtF2ae:DOCKER_USERNAME"
    DOCKER_PASSWORD: "arn:aws:secretsmanager:ap-south-1:825765401880:secret:Docker-Credentials-JtF2ae:DOCKER_PASSWORD"

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $DOCKER_USERNAME/client:latest .
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKER_USERNAME/client:latest

  post_build:
    commands:
      - echo "Deploying to EC2 instance..."
      - ssh -i /path/to/your/private-key.pem ec2-user@${EC2_HOST} << EOF
          docker pull $DOCKER_USERNAME/client:latest
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 3000:3000 $DOCKER_USERNAME/client:latest
        EOF
      - echo "Deployment complete!"

artifacts:
  files:
    - '**/*'
