name: Build and Deploy to aws ECS

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: ["closed"]

jobs:
  build-and-trigger-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4

    - name: Log files 
      run: ls -al
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker image to Docker Hub Registry.
      uses: docker/build-push-action@v6
      with: 
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:latest
        build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_BUILD_API_URL=${{ secrets.NEXT_PUBLIC_BUILD_API_URL }}